class Config:
    grammarPath = "D:\python\pythonProject\input\grammar.txt"
    lexInputPath = "D:\python\pythonProject\input\code.txt"
    formulaPath = "D:\python\pythonProject\output\文法.tsv"
    firstTablePath = "D:\python\pythonProject\output\First集合.tsv"
    followTablePath = "D:\python\pythonProject\output\Follow集合.tsv"
    predictMapPath = "D:\python\pythonProject\output\分析表.tsv"
    terminalPath = "D:\python\pythonProject\output\终结符.tsv"
    nonTerminalPath = "D:\python\pythonProject\output\非终结符.tsv"
    lexiconMiddleResult = "D:\python\pythonProject\output\词法分析产生的中间结果.tsv"
    parseResultPath = "D:\python\pythonProject\\result\gra.tsv"
    lexiconResultPath = "D:\python\pythonProject\\result\lex.tsv"
    initSymbol = "program"
